import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const miteraFont = localFont({
  src: "../public/fonts/mitera/Mitera-Regular.otf",
  variable: "--font-mitera",
  display: "swap",
});

const neueMontrealFont = localFont({
  src: [
    {
      path: "../public/fonts/neue-montreal/NeueMontreal-Regular.otf",
      weight: "400",
    },
    {
      path: "../public/fonts/neue-montreal/NeueMontreal-Medium.otf",
      weight: "500",
    },
    {
      path: "../public/fonts/neue-montreal/NeueMontreal-Medium.otf",
      weight: "600",
    },
    {
      path: "../public/fonts/neue-montreal/NeueMontreal-Bold.otf",
      weight: "700",
    },
  ],
  variable: "--font-neue-montreal",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${miteraFont.variable} ${neueMontrealFont.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
